name: main

on:
  push:
    branches-ignore:
    - main
    - gh-pages

jobs:
  test-noauth:
    runs-on: ubuntu-latest
    services:
      api:
        image: ghcr.io/flux-framework/flux-restful-api:latest
        ports:
          - 5000:5000
    steps:
    - uses: actions/checkout@v3
    - name: Run tests without auth
      run: |
        cd clients/python
        pip install -e .
        flux start pytest -xs flux_restful_client/tests/test_api.py

  test-auth:
    runs-on: ubuntu-latest
    services:
      api:
        env:
          FLUX_USER: fluxuser
          FLUX_TOKEN: "12345"
          FLUX_REQUIRE_AUTH: true
        image: ghcr.io/flux-framework/flux-restful-api:latest
        ports:
          - 5000:5000
    steps:
    - uses: actions/checkout@v3
    - name: Run tests with auth
      run: |
        cd clients/python
        pip install -e .
        export FLUX_USER=fluxuser
        export FLUX_TOKEN=12345
        flux start pytest -xs flux_restful_client/tests/test_api.py
