name: Test flux-restful-api

on:
  pull_request: []

jobs:
  prepare-container:
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.extract_branch.outputs.branch }}
    steps:
    - name: Extract branch name
      run: echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_OUTPUT
      id: extract_branch

  test:
    runs-on: ubuntu-latest
    needs: [prepare-container]
    container:
      image: ghcr.io/flux-framework/flux-restful-api:latest
      ports:
       - 5000
      env:
        INSTALL_BRANCH: ${{ needs.prepare-container.outputs.branch }}
        INSTALL_REPO: ${{ github.repository }}
    steps:
    - uses: actions/checkout@v3
    - name: Install Dependencies (in case changes)
      run: pip install -r requirements.txt
    - name: Run tests
      run: |
        flux start pytest -xs tests/test_api.py
        export FLUX_REQUIRE_AUTH=true
        export TEST_AUTH=true
        flux start pytest -xs tests/test_api.py
        export TEST_PAM_AUTH=true
        export TEST_PAM_AUTH_FAIL=true
        export FLUX_ENABLE_PAM=true
        flux start pytest -xs tests/test_api.py
        # Create the user and pass (should be successful)
        sudo useradd -m -p $(openssl passwd '12345') "fluxuser" || echo "Already exists."
        export TEST_PAM_AUTH=true
        export TEST_PAM_AUTH_FAIL=false
        flux start pytest -xs tests/test_api.py
